MOUSEKEY_ENABLE = yes       # Mouse keys(+4700)
EXTRAKEY_ENABLE = yes       # Audio control and System control(+450)
CONSOLE_ENABLE = no         # Console for debug(+400)
COMMAND_ENABLE = no        # Commands for debug and configuration
BACKLIGHT_ENABLE = yes       # Enable keyboard backlight functionality
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
TAP_DANCE_ENABLE = yes
RGBLIGHT_ENABLE = no   # Enable keyboard underlight functionality (+4870)

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
