TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
ADAFRUIT_BLE_ENABLE = yes

CONSOLE_ENABLE = yes         # Console for debug(+400)
COMMAND_ENABLE = no        # Commands for debug and configuration
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality

EXTRAKEY_ENABLE = no       # Audio control and System control(+450)

ifndef QUANTUM_DIR
	include ../../../../Makefile
endif
